trigger:
  branches:
    include:
      - main                           # <- select branch

  paths:
    include:
    - authentication_app_backend/**


pool:
  vmImage: "ubuntu-latest"

stages:
  # Stage 1: Testing
  - stage: TestStage
    displayName: "Testing Backend"
    jobs:
      - job: TestBackend
        displayName: "Run Backend Tests"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "18.x"
            displayName: "Install Node.js"

          - script: |    
              cd .        
              npm install
              npm test
            displayName: "Backend Tests"

  # Stage 2: Build and Push Docker Images
  - stage: BuildStage
    displayName: "Build and Push Docker Images"
    dependsOn: TestStage
    jobs:
      - job: BuildBackendImage
        displayName: "Build and Push Backend Docker Image"
        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: "20.10.24"
            displayName: "Install Docker"

          - task: Docker@2
            displayName: "Login to DockerHub"
            inputs:
              command: login
              containerRegistry: Dockerhub-Connection

          - script: |
              docker build -t "samahmoe/api-auth-app:latest" .
              docker push "samahmoe/api-auth-app:latest"
            displayName: "Build and Push Backend Image"