trigger:
  branches:
    include:
      - main                           # <- select branch

  paths:
    include:
    - authentication_app_frontend/**


stages:
  # Stage 1: Testing
  - stage: TestStage
    displayName: "Testing Frontend"
    jobs:
      - job: TestFrontend
        displayName: "Run Frontend Tests"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "18.x"
            displayName: "Install Node.js"

          - script: |
              npm install
              npm test
            displayName: "Frontend Tests"

  # Stage 2: Build and Push Docker Images
  - stage: BuildStage
    displayName: "Build and Push Docker Images"
    dependsOn: TestStage
    jobs:
      - job: BuildFrontendImage
        displayName: "Build Frontend Docker Image"
        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: "20.10.24"

          - task: Docker@2
            displayName: "Login to DockerHub"
            inputs:
              command: login
              containerRegistry: dockerhub_connection

          - script: |
              docker build -t "imagename" .
              docker push "imagename"
            displayName: "Build and Push Frontend"