trigger:
  branches:
    include:
      - main

  paths:
    include:
      - authentication_app_frontend/**

stages:
  # Stage 1: Testing
  - stage: TestStage
    displayName: "Testing Frontend"
    jobs:
      - job: TestFrontend
        displayName: "Run Frontend Tests"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "18.x"
            displayName: "Install Node.js"

          - script: |
              npm install
              npm test
            displayName: "Frontend Tests"
            workingDirectory: authentication_app_frontend  # ✅ تصحيح المسار

  # Stage 2: Build and Push Docker Images
  - stage: BuildStage
    displayName: "Build and Push Docker Images"
    dependsOn: TestStage
    jobs:
      - job: BuildFrontendImage
        displayName: "Build Frontend Docker Image"
        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: "20.10.24"

          - task: Docker@2
            displayName: "Login to DockerHub"
            inputs:
              command: login
              containerRegistry: Dockerhub-Connection

          - script: |
              docker build -t "samahmoe/ui-auth-app:latest" .
              docker push "samahmoe/ui-auth-app:latest"
            displayName: "Build and Push Frontend"
