trigger:
  branches:
    include:
      - main                           # <- select branch

  paths:
    include:
    -  kubernetes/**

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'Get AKS credentials and deploy manifests'
  inputs:
    azureSubscription: 'AzureServiceConnection'  # Replace with your service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Getting AKS credentials..."
      az aks get-credentials --resource-group Devops1-week12-Techmomentum-RG --name Devops1-week12-Techmomentum-aks-cluster --overwrite-existing
      
      bash ./deploy.sh

  workingDirectory: kubernetes  
