apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend-deploy
 labels:
   app: backend-app
 namespace: techMomentum-project3
spec:
 replicas: 2
 selector:
   matchLabels:
     app: backend-app
 template:
   metadata:
     name: backend-app
     labels:
       app: backend-app
   spec:
     containers:
       - name: backend-app
         image: afrah3b/api-project-trainer-portal:latest
         ports:
           - containerPort: 3000
         env:
           - name: DB_SERVER
             value: "devops1-week10-afrah-sqlserver.database.windows.net"
           - name: DB_USER
             value: "afrah"
           - name: DB_PASSWORD
             value: "password123456@"
           - name: DB_NAME
             value: "devops1-week10-afrah-sqldb"
