apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend-deploy
 labels:
   app: backend-app
 namespace: techmomentum-project
spec:
 replicas: 2
 selector:
   matchLabels:
     app: backend-app
 template:
   metadata:
     name: backend-app
     labels:
       app: backend-app
   spec:
     containers:
       - name: backend-app
         image: samahmoe/api-auth-app:latest
         ports:
           - containerPort: 3000
         env:
           - name: DB_SERVER
             value: "tch-sql-servertest.database.windows.net"
           - name: DB_USER
             value: "sqladmin"
           - name: DB_PASSWORD
             value: "HitechP@ssyes2025"
           - name: DB_NAME
             value: "tch-sql-databasetest"
