apiVersion: v1
kind: Service
metadata:
 name: frontend-clusterip-service
 namespace: techmomentum-project
spec:
 type: ClusterIP
 ports:
   - port: 80
     targetPort: 3000
 selector:
   app: frontend-app